#!/bin/sh

export TSLIB_TSDEVICE=/dev/input/event1
export QWS_MOUSE_PROTO=tslib:/dev/input/event1
export LD_LIBRARY_PATH=/usr/local/tslib/lib:$LD_LIBRARY_PATH
export TSLIB_FBDEVICE=/dev/fb0
export TSLIB_PLUGINDIR=/usr/local/tslib/lib/ts
export TSLIB_CONSOLEDEVICE=none
export TSLIB_CONFFILE=/usr/local/tslib/etc/ts.conf
export POINTERCAL_FILE=/etc/pointercal
export TSLIB_CALIBFILE=/etc/pointercal
export QWS_KEYBOARD=TTY:/dev/tty1
export KDEDIR=/opt/kde
export HOME=/root

mv /usr/bst/SYSTEM/Middleware/Tslib/calibrate/*  /etc/

ETCDIR=/etc
CALIBRATE=YES
for z in $(ls $ETCDIR)
do
    TSFile=$ETCDIR"/"$z
    if [ -f "$TSFile" ];then
        echo "$TSFile"
        if [ "$z"x = "pointercal"x ]; then
            CALIBRATE=NO
        fi
    fi
done

if [ "$CALIBRATE"x = "YES"x ]; then
	cd /usr/local/tslib/bin/
	./ts_calibrate
	cd /
fi


