
/* File generated by gen_cfile.py. Should not be modified. */

#include "display.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 Display_parameters_ORIENTATION = 0x0;		/* Mapped at index 0x2000, subindex 0x01 */
UNS8 Display_parameters_CONTRASTE = 0x7F;		/* Mapped at index 0x2000, subindex 0x02 */
UNS8 Display_parameters_BACKLIGHT = 0xFF;		/* Mapped at index 0x2000, subindex 0x03 */
UNS8 Display_parameters_VIT_SCROL = 0x3;		/* Mapped at index 0x2000, subindex 0x04 */
UNS8 Customer_Logo_LOGO_CLIENT = 0x0;		/* Mapped at index 0x2001, subindex 0x01 */
UNS8 Customer_Logo_LOGO_PERIODE = 0x5;		/* Mapped at index 0x2001, subindex 0x02 */
UNS8 Customer_Logo_LOGO_DECLENCHEMENT = 0x5;		/* Mapped at index 0x2001, subindex 0x03 */
UNS8 empty_objects_Bit = 0x0;		/* Mapped at index 0x200F, subindex 0x01 */
UNS8 empty_objects_UNS8 = 0x0;		/* Mapped at index 0x200F, subindex 0x02 */
UNS16 empty_objects_UNS16 = 0x0;		/* Mapped at index 0x200F, subindex 0x03 */
UNS24 empty_objects_UNS24 = 0x0;		/* Mapped at index 0x200F, subindex 0x04 */
UNS32 empty_objects_UNS32 = 0x0;		/* Mapped at index 0x200F, subindex 0x05 */
UNS8 Panel_input_Level_E_BC0 = 0x0;		/* Mapped at index 0x2100, subindex 0x01 */
UNS8 Panel_input_Level_E_BC1 = 0x0;		/* Mapped at index 0x2100, subindex 0x02 */
UNS8 Panel_input_Level_E_BC2 = 0x0;		/* Mapped at index 0x2100, subindex 0x03 */
UNS8 Panel_input_Level_E_BC3 = 0x0;		/* Mapped at index 0x2100, subindex 0x04 */
UNS8 Panel_input_Level_E_BC4 = 0x0;		/* Mapped at index 0x2100, subindex 0x05 */
UNS8 Panel_input_Level_E_BC5 = 0x0;		/* Mapped at index 0x2100, subindex 0x06 */
UNS8 Panel_input_Level_E_BC6 = 0x0;		/* Mapped at index 0x2100, subindex 0x07 */
UNS8 Panel_input_Level_E_BC7 = 0x0;		/* Mapped at index 0x2100, subindex 0x08 */
UNS8 Panel_input_Level_E_BC8 = 0x0;		/* Mapped at index 0x2100, subindex 0x09 */
UNS8 Panel_input_Level_E_BC9 = 0x0;		/* Mapped at index 0x2100, subindex 0x0A */
UNS8 Panel_input_Level_E_BC10 = 0x0;		/* Mapped at index 0x2100, subindex 0x0B */
UNS8 Panel_input_Level_E_BC11 = 0x0;		/* Mapped at index 0x2100, subindex 0x0C */
UNS8 Panel_input_Level_E_BC12 = 0x0;		/* Mapped at index 0x2100, subindex 0x0D */
UNS8 Panel_input_Level_E_BC13 = 0x0;		/* Mapped at index 0x2100, subindex 0x0E */
UNS8 Panel_input_Level_E_BC14 = 0x0;		/* Mapped at index 0x2100, subindex 0x0F */
UNS8 Panel_input_Other_E_REOUA = 0x0;		/* Mapped at index 0x2101, subindex 0x01 */
UNS8 Panel_input_Other_E_LIB1 = 0x0;		/* Mapped at index 0x2101, subindex 0x02 */
UNS8 Panel_input_Other_E_BFR = 0x0;		/* Mapped at index 0x2101, subindex 0x03 */
UNS8 Panel_input_Other_E_PCA = 0x0;		/* Mapped at index 0x2101, subindex 0x04 */
UNS8 Display_state_SUR = 0x0;		/* Mapped at index 0x2102, subindex 0x01 */
UNS8 Display_state_PARAM_AFF = 0x0;		/* Mapped at index 0x2102, subindex 0x02 */
UNS8 Display_state_EXT1 = 0x0;		/* Mapped at index 0x2102, subindex 0x03 */
UNS8 Display_state_EXT2 = 0x0;		/* Mapped at index 0x2102, subindex 0x04 */
UNS8 Display_state_EXT3 = 0x0;		/* Mapped at index 0x2102, subindex 0x05 */
UNS8 Display_state_DETECT_ALIM = 0x1;		/* Mapped at index 0x2102, subindex 0x06 */
UNS8 Display_state_PRESENCE_SD = 0x0;		/* Mapped at index 0x2102, subindex 0x07 */
UNS8 Display_state_libre = 0x0;		/* Mapped at index 0x2102, subindex 0x08 */
UNS8 Extension_input_E_EXT1 = 0x0;		/* Mapped at index 0x2103, subindex 0x01 */
UNS8 Extension_input_E_EXT2 = 0x0;		/* Mapped at index 0x2103, subindex 0x02 */
UNS8 Extension_input_E_EXT3 = 0x0;		/* Mapped at index 0x2103, subindex 0x03 */
UNS8 Extension_input_E_EXT4 = 0x0;		/* Mapped at index 0x2103, subindex 0x04 */
UNS8 Extension_input_E_EXT5 = 0x0;		/* Mapped at index 0x2103, subindex 0x05 */
UNS8 Extension_input_E_EXT6 = 0x0;		/* Mapped at index 0x2103, subindex 0x06 */
UNS8 Extension_input_E_EXT7 = 0x0;		/* Mapped at index 0x2103, subindex 0x07 */
UNS8 Extension_input_E_EXT8 = 0x0;		/* Mapped at index 0x2103, subindex 0x08 */
UNS8 Extension_input_E_EXT9 = 0x0;		/* Mapped at index 0x2103, subindex 0x09 */
UNS8 Extension_input_E_EXT10 = 0x0;		/* Mapped at index 0x2103, subindex 0x0A */
UNS8 Extension_input_E_EXT11 = 0x0;		/* Mapped at index 0x2103, subindex 0x0B */
UNS8 Extension_input_E_EXT12 = 0x0;		/* Mapped at index 0x2103, subindex 0x0C */
UNS8 Extension_input_E_EXT13 = 0x0;		/* Mapped at index 0x2103, subindex 0x0D */
UNS8 Extension_input_E_EXT14 = 0x0;		/* Mapped at index 0x2103, subindex 0x0E */
UNS8 Extension_input_E_EXT15 = 0x0;		/* Mapped at index 0x2103, subindex 0x0F */
UNS8 Extension_input_E_EXT16 = 0x0;		/* Mapped at index 0x2103, subindex 0x10 */
UNS8 Extension_input_E_EXT17 = 0x0;		/* Mapped at index 0x2103, subindex 0x11 */
UNS8 Extension_input_E_EXT18 = 0x0;		/* Mapped at index 0x2103, subindex 0x12 */
UNS8 Extension_input_E_EXT19 = 0x0;		/* Mapped at index 0x2103, subindex 0x13 */
UNS8 Extension_input_E_EXT20 = 0x0;		/* Mapped at index 0x2103, subindex 0x14 */
UNS8 Extension_input_E_EXT21 = 0x0;		/* Mapped at index 0x2103, subindex 0x15 */
UNS8 Extension_input_E_EXT22 = 0x0;		/* Mapped at index 0x2103, subindex 0x16 */
UNS8 Extension_input_E_EXT23 = 0x0;		/* Mapped at index 0x2103, subindex 0x17 */
UNS8 Extension_input_E_EXT24 = 0x0;		/* Mapped at index 0x2103, subindex 0x18 */
UNS8 Panel_output_Level_S_BC0 = 0x0;		/* Mapped at index 0x2200, subindex 0x01 */
UNS8 Panel_output_Level_S_BC1 = 0x0;		/* Mapped at index 0x2200, subindex 0x02 */
UNS8 Panel_output_Level_S_BC2 = 0x0;		/* Mapped at index 0x2200, subindex 0x03 */
UNS8 Panel_output_Level_S_BC3 = 0x0;		/* Mapped at index 0x2200, subindex 0x04 */
UNS8 Panel_output_Level_S_BC4 = 0x0;		/* Mapped at index 0x2200, subindex 0x05 */
UNS8 Panel_output_Level_S_BC5 = 0x0;		/* Mapped at index 0x2200, subindex 0x06 */
UNS8 Panel_output_Level_S_BC6 = 0x0;		/* Mapped at index 0x2200, subindex 0x07 */
UNS8 Panel_output_Level_S_BC7 = 0x0;		/* Mapped at index 0x2200, subindex 0x08 */
UNS8 Panel_output_Level_S_BC8 = 0x0;		/* Mapped at index 0x2200, subindex 0x09 */
UNS8 Panel_output_Level_S_BC9 = 0x0;		/* Mapped at index 0x2200, subindex 0x0A */
UNS8 Panel_output_Level_S_BC10 = 0x0;		/* Mapped at index 0x2200, subindex 0x0B */
UNS8 Panel_output_Level_S_BC11 = 0x0;		/* Mapped at index 0x2200, subindex 0x0C */
UNS8 Panel_output_Level_S_BC12 = 0x0;		/* Mapped at index 0x2200, subindex 0x0D */
UNS8 Panel_output_Level_S_BC13 = 0x0;		/* Mapped at index 0x2200, subindex 0x0E */
UNS8 Panel_output_Level_S_BC14 = 0x0;		/* Mapped at index 0x2200, subindex 0x0F */
UNS8 Panel_output_Other_S_LIB1 = 0x0;		/* Mapped at index 0x2201, subindex 0x01 */
UNS8 Panel_output_Other_S_LIB2 = 0x0;		/* Mapped at index 0x2201, subindex 0x02 */
UNS8 Panel_output_Other_S_LIB3 = 0x0;		/* Mapped at index 0x2201, subindex 0x03 */
UNS8 Panel_output_Other_S_LIB4 = 0x0;		/* Mapped at index 0x2201, subindex 0x04 */
UNS8 Display_Mode_AFF_EN = 0x1;		/* Mapped at index 0x2202, subindex 0x01 */
UNS8 Display_Mode_FCT_AFF = 0x0;		/* Mapped at index 0x2202, subindex 0x02 */
UNS8 Extension_output_S_EXT1 = 0x0;		/* Mapped at index 0x2203, subindex 0x01 */
UNS8 Extension_output_S_EXT2 = 0x0;		/* Mapped at index 0x2203, subindex 0x02 */
UNS8 Extension_output_S_EXT3 = 0x0;		/* Mapped at index 0x2203, subindex 0x03 */
UNS8 Extension_output_S_EXT4 = 0x0;		/* Mapped at index 0x2203, subindex 0x04 */
UNS8 Extension_output_S_EXT5 = 0x0;		/* Mapped at index 0x2203, subindex 0x05 */
UNS8 Extension_output_S_EXT6 = 0x0;		/* Mapped at index 0x2203, subindex 0x06 */
UNS8 Extension_output_S_EXT7 = 0x0;		/* Mapped at index 0x2203, subindex 0x07 */
UNS8 Extension_output_S_EXT8 = 0x0;		/* Mapped at index 0x2203, subindex 0x08 */
UNS8 Extension_output_S_EXT9 = 0x0;		/* Mapped at index 0x2203, subindex 0x09 */
UNS8 Extension_output_S_EXT10 = 0x0;		/* Mapped at index 0x2203, subindex 0x0A */
UNS8 Extension_output_S_EXT11 = 0x0;		/* Mapped at index 0x2203, subindex 0x0B */
UNS8 Extension_output_S_EXT12 = 0x0;		/* Mapped at index 0x2203, subindex 0x0C */
UNS8 Extension_output_S_EXT13 = 0x0;		/* Mapped at index 0x2203, subindex 0x0D */
UNS8 Extension_output_S_EXT14 = 0x0;		/* Mapped at index 0x2203, subindex 0x0E */
UNS8 Extension_output_S_EXT15 = 0x0;		/* Mapped at index 0x2203, subindex 0x0F */
UNS8 Extension_output_S_EXT16 = 0x0;		/* Mapped at index 0x2203, subindex 0x10 */
UNS8 Extension_output_S_EXT17 = 0x0;		/* Mapped at index 0x2203, subindex 0x11 */
UNS8 Extension_output_S_EXT18 = 0x0;		/* Mapped at index 0x2203, subindex 0x12 */
UNS8 Extension_output_S_EXT19 = 0x0;		/* Mapped at index 0x2203, subindex 0x13 */
UNS8 Extension_output_S_EXT20 = 0x0;		/* Mapped at index 0x2203, subindex 0x14 */
UNS8 Extension_output_S_EXT21 = 0x0;		/* Mapped at index 0x2203, subindex 0x15 */
UNS8 Extension_output_S_EXT22 = 0x0;		/* Mapped at index 0x2203, subindex 0x16 */
UNS8 Extension_output_S_EXT23 = 0x0;		/* Mapped at index 0x2203, subindex 0x17 */
UNS8 Extension_output_S_EXT24 = 0x0;		/* Mapped at index 0x2203, subindex 0x18 */
UNS8 Arrows_FLM = 0x0;		/* Mapped at index 0x2204, subindex 0x01 */
UNS8 Arrows_FLD = 0x0;		/* Mapped at index 0x2204, subindex 0x02 */
UNS8 Arrows_SCROL = 0x0;		/* Mapped at index 0x2204, subindex 0x03 */
UNS8 Sound_BUZ = 0x0;		/* Mapped at index 0x2205, subindex 0x01 */
UNS8 Sound_VOLUME_VOLUME_BIP = 0x88;		/* Mapped at index 0x2205, subindex 0x02 */
UNS8 Sound_NR_SON = 0xFF;		/* Mapped at index 0x2205, subindex 0x03 */
UNS8 Sound_VOLUME_MUSIQUE = 0x4;		/* Mapped at index 0x2205, subindex 0x04 */
UNS8 Sound_libre = 0x0;		/* Mapped at index 0x2205, subindex 0x05 */
UNS8 Level_text_Logo_NIV_ALPHA_1 = 0x0;		/* Mapped at index 0x2206, subindex 0x01 */
UNS8 Level_text_Logo_NIV_ALPHA_2 = 0x0;		/* Mapped at index 0x2206, subindex 0x02 */
UNS8 Level_text_Logo_NIV_ALPHA_3 = 0x0;		/* Mapped at index 0x2206, subindex 0x03 */
UNS8 Level_text_Logo_LOGO = 0x0;		/* Mapped at index 0x2206, subindex 0x04 */
UNS8 text_segmented_1_MSG1_LIGNE = 0x0;		/* Mapped at index 0x220A, subindex 0x01 */
UNS8 text_segmented_1_MSG1_COLONNE = 0x0;		/* Mapped at index 0x220A, subindex 0x02 */
UNS8 text_segmented_1_MSG1_CHAR1 = 0x0;		/* Mapped at index 0x220A, subindex 0x03 */
UNS8 text_segmented_1_MSG1_CHAR2 = 0x0;		/* Mapped at index 0x220A, subindex 0x04 */
UNS8 text_segmented_1_MSG1_CHAR3 = 0x0;		/* Mapped at index 0x220A, subindex 0x05 */
UNS8 text_segmented_1_MSG1_CHAR4 = 0x0;		/* Mapped at index 0x220A, subindex 0x06 */
UNS8 text_segmented_1_MSG1_CHAR5 = 0x0;		/* Mapped at index 0x220A, subindex 0x07 */
UNS8 text_segmented_1_MSG1_CHAR6 = 0x0;		/* Mapped at index 0x220A, subindex 0x08 */
UNS8 texte_segmented_2_MSG2_LIGNE = 0x0;		/* Mapped at index 0x220B, subindex 0x01 */
UNS8 texte_segmented_2_MSG2_COLONNE = 0x0;		/* Mapped at index 0x220B, subindex 0x02 */
UNS8 texte_segmented_2_MSG2_CHAR1 = 0x0;		/* Mapped at index 0x220B, subindex 0x03 */
UNS8 texte_segmented_2_MSG2_CHAR2 = 0x0;		/* Mapped at index 0x220B, subindex 0x04 */
UNS8 texte_segmented_2_MSG2_CHAR3 = 0x0;		/* Mapped at index 0x220B, subindex 0x05 */
UNS8 texte_segmented_2_MSG2_CHAR4 = 0x0;		/* Mapped at index 0x220B, subindex 0x06 */
UNS8 texte_segmented_2_MSG2_CHAR5 = 0x0;		/* Mapped at index 0x220B, subindex 0x07 */
UNS8 texte_segmented_2_MSG2_CHAR6 = 0x0;		/* Mapped at index 0x220B, subindex 0x08 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 display_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 display_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 display_iam_a_slave = 1;

TIMER_HANDLE display_heartBeatTimers[1] = {TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 display_obj1000 = 0x1A1;	/* 417 */
                    subindex display_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&display_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 display_obj1001 = 0x0;	/* 0 */
                    subindex display_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 display_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 display_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t display_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex display_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&display_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&display_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 display_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 display_obj1006 = 0x0;   /* 0 */

/* index 0x1008 :   Manufacturer Device Name. */
                    UNS8 display_obj1008[32] = "DISPLAY_NAME";
                    subindex display_Index1008[] = 
                     {
                       { RO, visible_string, 32, (void*)&display_obj1008 }
                     };

/* index 0x1009 :   Manufacturer Hardware Version. */
                    UNS8 display_obj1009[32] = "1.0.0";
                    subindex display_Index1009[] = 
                     {
                       { RO, visible_string, 32, (void*)&display_obj1009 }
                     };

/* index 0x100A :   Manufacturer Software Version. */
                    UNS8 display_obj100A[32] = "1.0.0";
                    subindex display_Index100A[] = 
                     {
                       { RO, visible_string, 32, (void*)&display_obj100A }
                     };

/* index 0x100C :   Guard Time. */
                    UNS16 display_obj100C = 0x0;	/* 0 */
                    subindex display_Index100C[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&display_obj100C }
                     };

/* index 0x100D :   Life Time Factor. */
                    UNS8 display_obj100D = 0x0;	/* 0 */
                    subindex display_Index100D[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj100D }
                     };

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 display_obj1014 = 0x80;	/* 128 */
                    subindex display_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 display_highestSubIndex_obj1016 = 1; /* number of subindex - 1*/
                    UNS32 display_obj1016[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex display_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj1016 },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1016[0] }
                     };

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 display_obj1017 = 0x0;	/* 0 */
                    ODCallback_t display_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex display_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&display_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 display_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 display_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 display_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 display_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 display_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex display_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&display_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&display_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&display_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&display_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 display_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 display_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 display_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex display_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&display_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&display_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 display_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 display_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x60A;	/* 1546 */
                    UNS32 display_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x58A;	/* 1418 */
                    UNS8 display_obj1280_Node_ID_of_the_SDO_Server = 0xA;	/* 10 */
                    subindex display_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 display_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 display_obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 display_obj1400_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 display_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 display_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 display_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 display_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex display_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&display_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&display_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 display_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 display_obj1401_COB_ID_used_by_PDO = 0x300;	/* 768 */
                    UNS8 display_obj1401_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 display_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 display_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 display_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 display_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex display_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&display_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&display_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 display_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 display_obj1402_COB_ID_used_by_PDO = 0x400;	/* 1024 */
                    UNS8 display_obj1402_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 display_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 display_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 display_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 display_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex display_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&display_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&display_obj1402_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1402_SYNC_start_value }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 display_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 display_obj1403_COB_ID_used_by_PDO = 0x500;	/* 1280 */
                    UNS8 display_obj1403_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 display_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 display_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 display_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 display_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex display_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&display_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&display_obj1403_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1403_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 display_highestSubIndex_obj1600 = 50; /* number of subindex - 1*/
                    UNS32 display_obj1600[] = 
                    {
                      0x22000101,	/* 570425601 */
                      0x22000201,	/* 570425857 */
                      0x22000301,	/* 570426113 */
                      0x22000401,	/* 570426369 */
                      0x22000501,	/* 570426625 */
                      0x22000601,	/* 570426881 */
                      0x22000701,	/* 570427137 */
                      0x22000801,	/* 570427393 */
                      0x22000901,	/* 570427649 */
                      0x22000A01,	/* 570427905 */
                      0x22000B01,	/* 570428161 */
                      0x22000C01,	/* 570428417 */
                      0x22040101,	/* 570687745 */
                      0x22040201,	/* 570688001 */
                      0x22040301,	/* 570688257 */
                      0x22050101,	/* 570753281 */
                      0x22020101,	/* 570556673 */
                      0x22020201,	/* 570556929 */
                      0x22010101,	/* 570491137 */
                      0x22010201,	/* 570491393 */
                      0x22010301,	/* 570491649 */
                      0x22010401,	/* 570491905 */
                      0x200F0101,	/* 537854209 */
                      0x200F0101,	/* 537854209 */
                      0x22030101,	/* 570622209 */
                      0x22030201,	/* 570622465 */
                      0x22030301,	/* 570622721 */
                      0x22030401,	/* 570622977 */
                      0x22030501,	/* 570623233 */
                      0x22030601,	/* 570623489 */
                      0x22030701,	/* 570623745 */
                      0x22030801,	/* 570624001 */
                      0x22030901,	/* 570624257 */
                      0x22030A01,	/* 570624513 */
                      0x22030B01,	/* 570624769 */
                      0x22030C01,	/* 570625025 */
                      0x22030D01,	/* 570625281 */
                      0x22030E01,	/* 570625537 */
                      0x22030F01,	/* 570625793 */
                      0x22031001,	/* 570626049 */
                      0x22031101,	/* 570626305 */
                      0x22031201,	/* 570626561 */
                      0x22031301,	/* 570626817 */
                      0x22031401,	/* 570627073 */
                      0x22031501,	/* 570627329 */
                      0x22031601,	/* 570627585 */
                      0x22031701,	/* 570627841 */
                      0x22031801,	/* 570628097 */
                      0x22050208,	/* 570753544 */
                      0x22050408	/* 570754056 */
                    };
                    ODCallback_t display_Index1600_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex display_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[7] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[8] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[9] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[10] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[11] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[12] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[13] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[14] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[15] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[16] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[17] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[18] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[19] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[20] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[21] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[22] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[23] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[24] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[25] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[26] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[27] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[28] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[29] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[30] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[31] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[32] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[33] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[34] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[35] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[36] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[37] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[38] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[39] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[40] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[41] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[42] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[43] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[44] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[45] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[46] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[47] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[48] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1600[49] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 display_highestSubIndex_obj1601 = 5; /* number of subindex - 1*/
                    UNS32 display_obj1601[] = 
                    {
                      0x22060108,	/* 570818824 */
                      0x22060208,	/* 570819080 */
                      0x22060308,	/* 570819336 */
                      0x22050308,	/* 570753800 */
                      0x22060401	/* 570819585 */
                    };
                    subindex display_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1601[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1601[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1601[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1601[4] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 display_highestSubIndex_obj1602 = 8; /* number of subindex - 1*/
                    UNS32 display_obj1602[] = 
                    {
                      0x220A0108,	/* 571080968 */
                      0x220A0208,	/* 571081224 */
                      0x220A0308,	/* 571081480 */
                      0x220A0408,	/* 571081736 */
                      0x220A0508,	/* 571081992 */
                      0x220A0608,	/* 571082248 */
                      0x220A0708,	/* 571082504 */
                      0x220A0808	/* 571082760 */
                    };
                    subindex display_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1602[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1602[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1602[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1602[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1602[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1602[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1602[7] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 display_highestSubIndex_obj1603 = 8; /* number of subindex - 1*/
                    UNS32 display_obj1603[] = 
                    {
                      0x220B0108,	/* 571146504 */
                      0x220B0208,	/* 571146760 */
                      0x220B0308,	/* 571147016 */
                      0x220B0408,	/* 571147272 */
                      0x220B0508,	/* 571147528 */
                      0x220B0608,	/* 571147784 */
                      0x220B0708,	/* 571148040 */
                      0x220B0808	/* 571148296 */
                    };
                    subindex display_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1603[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1603[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1603[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1603[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1603[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1603[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1603[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1603[7] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 display_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 display_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 display_obj1800_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 display_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 display_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 display_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 display_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t display_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex display_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&display_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&display_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1800_SYNC_start_value }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 display_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 display_obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 display_obj1801_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 display_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 display_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 display_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 display_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t display_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex display_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&display_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&display_obj1801_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1801_SYNC_start_value }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 display_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 display_obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 display_obj1802_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 display_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 display_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 display_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 display_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t display_Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex display_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&display_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&display_obj1802_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1802_SYNC_start_value }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 display_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 display_obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 display_obj1803_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 display_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 display_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 display_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 display_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t display_Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex display_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&display_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&display_obj1803_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&display_obj1803_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 display_highestSubIndex_obj1A00 = 49; /* number of subindex - 1*/
                    UNS32 display_obj1A00[] = 
                    {
                      0x21000101,	/* 553648385 */
                      0x21000201,	/* 553648641 */
                      0x21000301,	/* 553648897 */
                      0x21000401,	/* 553649153 */
                      0x21000501,	/* 553649409 */
                      0x21000601,	/* 553649665 */
                      0x21000701,	/* 553649921 */
                      0x21000801,	/* 553650177 */
                      0x21000901,	/* 553650433 */
                      0x21000A01,	/* 553650689 */
                      0x21000B01,	/* 553650945 */
                      0x21000C01,	/* 553651201 */
                      0x21010101,	/* 553713921 */
                      0x21010201,	/* 553714177 */
                      0x21010301,	/* 553714433 */
                      0x21010401,	/* 553714689 */
                      0x21020101,	/* 553779457 */
                      0x21020201,	/* 553779713 */
                      0x21020301,	/* 553779969 */
                      0x21020401,	/* 553780225 */
                      0x21020501,	/* 553780481 */
                      0x21020601,	/* 553780737 */
                      0x21020701,	/* 553780993 */
                      0x200F0101,	/* 537854209 */
                      0x21030101,	/* 553844993 */
                      0x21030201,	/* 553845249 */
                      0x21030301,	/* 553845505 */
                      0x21030401,	/* 553845761 */
                      0x21030501,	/* 553846017 */
                      0x21030601,	/* 553846273 */
                      0x21030701,	/* 553846529 */
                      0x21030801,	/* 553846785 */
                      0x21030901,	/* 553847041 */
                      0x21030A01,	/* 553847297 */
                      0x21030B01,	/* 553847553 */
                      0x21030C01,	/* 553847809 */
                      0x21030D01,	/* 553848065 */
                      0x21030E01,	/* 553848321 */
                      0x21030F01,	/* 553848577 */
                      0x21031001,	/* 553848833 */
                      0x21031101,	/* 553849089 */
                      0x21031201,	/* 553849345 */
                      0x21031301,	/* 553849601 */
                      0x21031401,	/* 553849857 */
                      0x21031501,	/* 553850113 */
                      0x21031601,	/* 553850369 */
                      0x21031701,	/* 553850625 */
                      0x21031801,	/* 553850881 */
                      0x200F0310	/* 537854736 */
                    };
                    subindex display_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[7] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[8] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[9] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[10] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[11] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[12] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[13] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[14] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[15] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[16] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[17] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[18] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[19] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[20] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[21] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[22] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[23] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[24] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[25] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[26] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[27] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[28] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[29] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[30] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[31] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[32] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[33] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[34] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[35] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[36] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[37] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[38] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[39] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[40] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[41] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[42] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[43] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[44] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[45] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[46] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[47] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A00[48] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 display_highestSubIndex_obj1A01 = 8; /* number of subindex - 1*/
                    UNS32 display_obj1A01[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex display_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A01[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A01[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A01[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A01[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A01[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A01[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A01[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A01[7] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 display_highestSubIndex_obj1A02 = 8; /* number of subindex - 1*/
                    UNS32 display_obj1A02[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex display_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj1A02 },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A02[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A02[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A02[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A02[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A02[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A02[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A02[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A02[7] }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 display_highestSubIndex_obj1A03 = 8; /* number of subindex - 1*/
                    UNS32 display_obj1A03[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex display_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj1A03 },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A03[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A03[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A03[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A03[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A03[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A03[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A03[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&display_obj1A03[7] }
                     };

/* index 0x2000 :   Mapped variable Display parameters */
                    UNS8 display_highestSubIndex_obj2000 = 4; /* number of subindex - 1*/
                    ODCallback_t Display_parameters_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex display_Index2000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj2000 },
                       { RW, uint8, sizeof (UNS8), (void*)&Display_parameters_ORIENTATION },
                       { RW, uint8, sizeof (UNS8), (void*)&Display_parameters_CONTRASTE },
                       { RW, uint8, sizeof (UNS8), (void*)&Display_parameters_BACKLIGHT },
                       { RW, uint8, sizeof (UNS8), (void*)&Display_parameters_VIT_SCROL }
                     };

/* index 0x2001 :   Mapped variable Customer Logo */
                    UNS8 display_highestSubIndex_obj2001 = 3; /* number of subindex - 1*/
                    ODCallback_t Customer_Logo_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex display_Index2001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj2001 },
                       { RW, uint8, sizeof (UNS8), (void*)&Customer_Logo_LOGO_CLIENT },
                       { RW, uint8, sizeof (UNS8), (void*)&Customer_Logo_LOGO_PERIODE },
                       { RW, uint8, sizeof (UNS8), (void*)&Customer_Logo_LOGO_DECLENCHEMENT }
                     };

/* index 0x200F :   Mapped variable empty objects */
                    UNS8 display_highestSubIndex_obj200F = 5; /* number of subindex - 1*/
                    ODCallback_t empty_objects_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex display_Index200F[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj200F },
                       { RW, boolean, sizeof (UNS8), (void*)&empty_objects_Bit },
                       { RW, uint8, sizeof (UNS8), (void*)&empty_objects_UNS8 },
                       { RW, uint16, sizeof (UNS16), (void*)&empty_objects_UNS16 },
                       { RW, uint24, sizeof (UNS24), (void*)&empty_objects_UNS24 },
                       { RW, uint32, sizeof (UNS32), (void*)&empty_objects_UNS32 }
                     };

/* index 0x2100 :   Mapped variable Panel input Level */
                    UNS8 display_highestSubIndex_obj2100 = 15; /* number of subindex - 1*/
                    ODCallback_t Panel_input_Level_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex display_Index2100[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj2100 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_input_Level_E_BC0 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_input_Level_E_BC1 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_input_Level_E_BC2 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_input_Level_E_BC3 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_input_Level_E_BC4 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_input_Level_E_BC5 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_input_Level_E_BC6 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_input_Level_E_BC7 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_input_Level_E_BC8 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_input_Level_E_BC9 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_input_Level_E_BC10 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_input_Level_E_BC11 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_input_Level_E_BC12 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_input_Level_E_BC13 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_input_Level_E_BC14 }
                     };

/* index 0x2101 :   Mapped variable Panel input Other */
                    UNS8 display_highestSubIndex_obj2101 = 4; /* number of subindex - 1*/
                    ODCallback_t Panel_input_Other_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex display_Index2101[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj2101 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_input_Other_E_REOUA },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_input_Other_E_LIB1 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_input_Other_E_BFR },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_input_Other_E_PCA }
                     };

/* index 0x2102 :   Mapped variable Display state */
                    UNS8 display_highestSubIndex_obj2102 = 8; /* number of subindex - 1*/
                    ODCallback_t Display_state_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex display_Index2102[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj2102 },
                       { RW, boolean, sizeof (UNS8), (void*)&Display_state_SUR },
                       { RW, boolean, sizeof (UNS8), (void*)&Display_state_PARAM_AFF },
                       { RW, boolean, sizeof (UNS8), (void*)&Display_state_EXT1 },
                       { RW, boolean, sizeof (UNS8), (void*)&Display_state_EXT2 },
                       { RW, boolean, sizeof (UNS8), (void*)&Display_state_EXT3 },
                       { RW, boolean, sizeof (UNS8), (void*)&Display_state_DETECT_ALIM },
                       { RW, boolean, sizeof (UNS8), (void*)&Display_state_PRESENCE_SD },
                       { RW, boolean, sizeof (UNS8), (void*)&Display_state_libre }
                     };

/* index 0x2103 :   Mapped variable Extension input */
                    UNS8 display_highestSubIndex_obj2103 = 24; /* number of subindex - 1*/
                    ODCallback_t Extension_input_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex display_Index2103[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj2103 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT1 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT2 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT3 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT4 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT5 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT6 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT7 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT8 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT9 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT10 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT11 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT12 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT13 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT14 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT15 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT16 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT17 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT18 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT19 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT20 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT21 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT22 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT23 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_input_E_EXT24 }
                     };

/* index 0x2200 :   Mapped variable Panel output Level */
                    UNS8 display_highestSubIndex_obj2200 = 15; /* number of subindex - 1*/
                    ODCallback_t Panel_output_Level_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex display_Index2200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj2200 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_output_Level_S_BC0 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_output_Level_S_BC1 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_output_Level_S_BC2 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_output_Level_S_BC3 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_output_Level_S_BC4 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_output_Level_S_BC5 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_output_Level_S_BC6 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_output_Level_S_BC7 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_output_Level_S_BC8 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_output_Level_S_BC9 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_output_Level_S_BC10 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_output_Level_S_BC11 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_output_Level_S_BC12 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_output_Level_S_BC13 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_output_Level_S_BC14 }
                     };

/* index 0x2201 :   Mapped variable Panel output Other */
                    UNS8 display_highestSubIndex_obj2201 = 4; /* number of subindex - 1*/
                    ODCallback_t Panel_output_Other_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex display_Index2201[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj2201 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_output_Other_S_LIB1 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_output_Other_S_LIB2 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_output_Other_S_LIB3 },
                       { RW, boolean, sizeof (UNS8), (void*)&Panel_output_Other_S_LIB4 }
                     };

/* index 0x2202 :   Mapped variable Display Mode */
                    UNS8 display_highestSubIndex_obj2202 = 2; /* number of subindex - 1*/
                    ODCallback_t Display_Mode_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex display_Index2202[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj2202 },
                       { RW, boolean, sizeof (UNS8), (void*)&Display_Mode_AFF_EN },
                       { RW, boolean, sizeof (UNS8), (void*)&Display_Mode_FCT_AFF }
                     };

/* index 0x2203 :   Mapped variable Extension output */
                    UNS8 display_highestSubIndex_obj2203 = 24; /* number of subindex - 1*/
                    ODCallback_t Extension_output_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex display_Index2203[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj2203 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT1 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT2 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT3 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT4 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT5 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT6 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT7 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT8 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT9 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT10 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT11 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT12 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT13 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT14 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT15 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT16 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT17 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT18 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT19 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT20 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT21 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT22 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT23 },
                       { RW, boolean, sizeof (UNS8), (void*)&Extension_output_S_EXT24 }
                     };

/* index 0x2204 :   Mapped variable Arrows */
                    UNS8 display_highestSubIndex_obj2204 = 3; /* number of subindex - 1*/
                    ODCallback_t Arrows_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex display_Index2204[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj2204 },
                       { RW, boolean, sizeof (UNS8), (void*)&Arrows_FLM },
                       { RW, boolean, sizeof (UNS8), (void*)&Arrows_FLD },
                       { RW, boolean, sizeof (UNS8), (void*)&Arrows_SCROL }
                     };

/* index 0x2205 :   Mapped variable Sound */
                    UNS8 display_highestSubIndex_obj2205 = 5; /* number of subindex - 1*/
                    ODCallback_t Sound_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex display_Index2205[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj2205 },
                       { RW, boolean, sizeof (UNS8), (void*)&Sound_BUZ },
                       { RW, uint8, sizeof (UNS8), (void*)&Sound_VOLUME_VOLUME_BIP },
                       { RW, uint8, sizeof (UNS8), (void*)&Sound_NR_SON },
                       { RW, uint8, sizeof (UNS8), (void*)&Sound_VOLUME_MUSIQUE },
                       { RW, uint8, sizeof (UNS8), (void*)&Sound_libre }
                     };

/* index 0x2206 :   Mapped variable Level text/Logo */
                    UNS8 display_highestSubIndex_obj2206 = 4; /* number of subindex - 1*/
                    ODCallback_t Level_text_Logo_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex display_Index2206[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj2206 },
                       { RW, uint8, sizeof (UNS8), (void*)&Level_text_Logo_NIV_ALPHA_1 },
                       { RW, uint8, sizeof (UNS8), (void*)&Level_text_Logo_NIV_ALPHA_2 },
                       { RW, uint8, sizeof (UNS8), (void*)&Level_text_Logo_NIV_ALPHA_3 },
                       { RW, boolean, sizeof (UNS8), (void*)&Level_text_Logo_LOGO }
                     };

/* index 0x220A :   Mapped variable text segmented 1 */
                    UNS8 display_highestSubIndex_obj220A = 8; /* number of subindex - 1*/
                    ODCallback_t text_segmented_1_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex display_Index220A[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj220A },
                       { RW, uint8, sizeof (UNS8), (void*)&text_segmented_1_MSG1_LIGNE },
                       { RW, uint8, sizeof (UNS8), (void*)&text_segmented_1_MSG1_COLONNE },
                       { RW, uint8, sizeof (UNS8), (void*)&text_segmented_1_MSG1_CHAR1 },
                       { RW, uint8, sizeof (UNS8), (void*)&text_segmented_1_MSG1_CHAR2 },
                       { RW, uint8, sizeof (UNS8), (void*)&text_segmented_1_MSG1_CHAR3 },
                       { RW, uint8, sizeof (UNS8), (void*)&text_segmented_1_MSG1_CHAR4 },
                       { RW, uint8, sizeof (UNS8), (void*)&text_segmented_1_MSG1_CHAR5 },
                       { RW, uint8, sizeof (UNS8), (void*)&text_segmented_1_MSG1_CHAR6 }
                     };

/* index 0x220B :   Mapped variable texte segmented 2 */
                    UNS8 display_highestSubIndex_obj220B = 8; /* number of subindex - 1*/
                    ODCallback_t texte_segmented_2_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex display_Index220B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&display_highestSubIndex_obj220B },
                       { RW, uint8, sizeof (UNS8), (void*)&texte_segmented_2_MSG2_LIGNE },
                       { RW, uint8, sizeof (UNS8), (void*)&texte_segmented_2_MSG2_COLONNE },
                       { RW, uint8, sizeof (UNS8), (void*)&texte_segmented_2_MSG2_CHAR1 },
                       { RW, uint8, sizeof (UNS8), (void*)&texte_segmented_2_MSG2_CHAR2 },
                       { RW, uint8, sizeof (UNS8), (void*)&texte_segmented_2_MSG2_CHAR3 },
                       { RW, uint8, sizeof (UNS8), (void*)&texte_segmented_2_MSG2_CHAR4 },
                       { RW, uint8, sizeof (UNS8), (void*)&texte_segmented_2_MSG2_CHAR5 },
                       { RW, uint8, sizeof (UNS8), (void*)&texte_segmented_2_MSG2_CHAR6 }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable display_objdict[] = 
{
  { (subindex*)display_Index1000,sizeof(display_Index1000)/sizeof(display_Index1000[0]), 0x1000},
  { (subindex*)display_Index1001,sizeof(display_Index1001)/sizeof(display_Index1001[0]), 0x1001},
  { (subindex*)display_Index1008,sizeof(display_Index1008)/sizeof(display_Index1008[0]), 0x1008},
  { (subindex*)display_Index1009,sizeof(display_Index1009)/sizeof(display_Index1009[0]), 0x1009},
  { (subindex*)display_Index100A,sizeof(display_Index100A)/sizeof(display_Index100A[0]), 0x100A},
  { (subindex*)display_Index100C,sizeof(display_Index100C)/sizeof(display_Index100C[0]), 0x100C},
  { (subindex*)display_Index100D,sizeof(display_Index100D)/sizeof(display_Index100D[0]), 0x100D},
  { (subindex*)display_Index1014,sizeof(display_Index1014)/sizeof(display_Index1014[0]), 0x1014},
  { (subindex*)display_Index1016,sizeof(display_Index1016)/sizeof(display_Index1016[0]), 0x1016},
  { (subindex*)display_Index1017,sizeof(display_Index1017)/sizeof(display_Index1017[0]), 0x1017},
  { (subindex*)display_Index1018,sizeof(display_Index1018)/sizeof(display_Index1018[0]), 0x1018},
  { (subindex*)display_Index1200,sizeof(display_Index1200)/sizeof(display_Index1200[0]), 0x1200},
  { (subindex*)display_Index1280,sizeof(display_Index1280)/sizeof(display_Index1280[0]), 0x1280},
  { (subindex*)display_Index1400,sizeof(display_Index1400)/sizeof(display_Index1400[0]), 0x1400},
  { (subindex*)display_Index1401,sizeof(display_Index1401)/sizeof(display_Index1401[0]), 0x1401},
  { (subindex*)display_Index1402,sizeof(display_Index1402)/sizeof(display_Index1402[0]), 0x1402},
  { (subindex*)display_Index1403,sizeof(display_Index1403)/sizeof(display_Index1403[0]), 0x1403},
  { (subindex*)display_Index1600,sizeof(display_Index1600)/sizeof(display_Index1600[0]), 0x1600},
  { (subindex*)display_Index1601,sizeof(display_Index1601)/sizeof(display_Index1601[0]), 0x1601},
  { (subindex*)display_Index1602,sizeof(display_Index1602)/sizeof(display_Index1602[0]), 0x1602},
  { (subindex*)display_Index1603,sizeof(display_Index1603)/sizeof(display_Index1603[0]), 0x1603},
  { (subindex*)display_Index1800,sizeof(display_Index1800)/sizeof(display_Index1800[0]), 0x1800},
  { (subindex*)display_Index1801,sizeof(display_Index1801)/sizeof(display_Index1801[0]), 0x1801},
  { (subindex*)display_Index1802,sizeof(display_Index1802)/sizeof(display_Index1802[0]), 0x1802},
  { (subindex*)display_Index1803,sizeof(display_Index1803)/sizeof(display_Index1803[0]), 0x1803},
  { (subindex*)display_Index1A00,sizeof(display_Index1A00)/sizeof(display_Index1A00[0]), 0x1A00},
  { (subindex*)display_Index1A01,sizeof(display_Index1A01)/sizeof(display_Index1A01[0]), 0x1A01},
  { (subindex*)display_Index1A02,sizeof(display_Index1A02)/sizeof(display_Index1A02[0]), 0x1A02},
  { (subindex*)display_Index1A03,sizeof(display_Index1A03)/sizeof(display_Index1A03[0]), 0x1A03},
  { (subindex*)display_Index2000,sizeof(display_Index2000)/sizeof(display_Index2000[0]), 0x2000},
  { (subindex*)display_Index2001,sizeof(display_Index2001)/sizeof(display_Index2001[0]), 0x2001},
  { (subindex*)display_Index200F,sizeof(display_Index200F)/sizeof(display_Index200F[0]), 0x200F},
  { (subindex*)display_Index2100,sizeof(display_Index2100)/sizeof(display_Index2100[0]), 0x2100},
  { (subindex*)display_Index2101,sizeof(display_Index2101)/sizeof(display_Index2101[0]), 0x2101},
  { (subindex*)display_Index2102,sizeof(display_Index2102)/sizeof(display_Index2102[0]), 0x2102},
  { (subindex*)display_Index2103,sizeof(display_Index2103)/sizeof(display_Index2103[0]), 0x2103},
  { (subindex*)display_Index2200,sizeof(display_Index2200)/sizeof(display_Index2200[0]), 0x2200},
  { (subindex*)display_Index2201,sizeof(display_Index2201)/sizeof(display_Index2201[0]), 0x2201},
  { (subindex*)display_Index2202,sizeof(display_Index2202)/sizeof(display_Index2202[0]), 0x2202},
  { (subindex*)display_Index2203,sizeof(display_Index2203)/sizeof(display_Index2203[0]), 0x2203},
  { (subindex*)display_Index2204,sizeof(display_Index2204)/sizeof(display_Index2204[0]), 0x2204},
  { (subindex*)display_Index2205,sizeof(display_Index2205)/sizeof(display_Index2205[0]), 0x2205},
  { (subindex*)display_Index2206,sizeof(display_Index2206)/sizeof(display_Index2206[0]), 0x2206},
  { (subindex*)display_Index220A,sizeof(display_Index220A)/sizeof(display_Index220A[0]), 0x220A},
  { (subindex*)display_Index220B,sizeof(display_Index220B)/sizeof(display_Index220B[0]), 0x220B},
};

const indextable * display_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1008: i = 2;break;
		case 0x1009: i = 3;break;
		case 0x100A: i = 4;break;
		case 0x100C: i = 5;break;
		case 0x100D: i = 6;break;
		case 0x1014: i = 7;break;
		case 0x1016: i = 8;break;
		case 0x1017: i = 9;*callbacks = display_Index1017_callbacks; break;
		case 0x1018: i = 10;break;
		case 0x1200: i = 11;break;
		case 0x1280: i = 12;break;
		case 0x1400: i = 13;break;
		case 0x1401: i = 14;break;
		case 0x1402: i = 15;break;
		case 0x1403: i = 16;break;
		case 0x1600: i = 17;*callbacks = display_Index1600_callbacks; break;
		case 0x1601: i = 18;break;
		case 0x1602: i = 19;break;
		case 0x1603: i = 20;break;
		case 0x1800: i = 21;*callbacks = display_Index1800_callbacks; break;
		case 0x1801: i = 22;*callbacks = display_Index1801_callbacks; break;
		case 0x1802: i = 23;*callbacks = display_Index1802_callbacks; break;
		case 0x1803: i = 24;*callbacks = display_Index1803_callbacks; break;
		case 0x1A00: i = 25;break;
		case 0x1A01: i = 26;break;
		case 0x1A02: i = 27;break;
		case 0x1A03: i = 28;break;
		case 0x2000: i = 29;*callbacks = Display_parameters_callbacks; break;
		case 0x2001: i = 30;*callbacks = Customer_Logo_callbacks; break;
		case 0x200F: i = 31;*callbacks = empty_objects_callbacks; break;
		case 0x2100: i = 32;*callbacks = Panel_input_Level_callbacks; break;
		case 0x2101: i = 33;*callbacks = Panel_input_Other_callbacks; break;
		case 0x2102: i = 34;*callbacks = Display_state_callbacks; break;
		case 0x2103: i = 35;*callbacks = Extension_input_callbacks; break;
		case 0x2200: i = 36;*callbacks = Panel_output_Level_callbacks; break;
		case 0x2201: i = 37;*callbacks = Panel_output_Other_callbacks; break;
		case 0x2202: i = 38;*callbacks = Display_Mode_callbacks; break;
		case 0x2203: i = 39;*callbacks = Extension_output_callbacks; break;
		case 0x2204: i = 40;*callbacks = Arrows_callbacks; break;
		case 0x2205: i = 41;*callbacks = Sound_callbacks; break;
		case 0x2206: i = 42;*callbacks = Level_text_Logo_callbacks; break;
		case 0x220A: i = 43;*callbacks = text_segmented_1_callbacks; break;
		case 0x220B: i = 44;*callbacks = texte_segmented_2_callbacks; break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &display_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status display_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index display_firstIndex = {
  11, /* SDO_SVR */
  12, /* SDO_CLT */
  13, /* PDO_RCV */
  17, /* PDO_RCV_MAP */
  21, /* PDO_TRS */
  25 /* PDO_TRS_MAP */
};

const quick_index display_lastIndex = {
  11, /* SDO_SVR */
  12, /* SDO_CLT */
  16, /* PDO_RCV */
  20, /* PDO_RCV_MAP */
  24, /* PDO_TRS */
  28 /* PDO_TRS_MAP */
};

const UNS16 display_ObjdictSize = sizeof(display_objdict)/sizeof(display_objdict[0]); 

CO_Data display_Data = CANOPEN_NODE_DATA_INITIALIZER(display);

